//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.DataProcessing
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_settings
    {
        public int id { get; set; }
        public string environment { get; set; }
        public string setting_name { get; set; }
        public string setting_value { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
