//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.DataProcessing
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_tracked_errors_local
    {
        public string Error_code { get; set; }
        public string error_message { get; set; }
        public bool crm { get; set; }
        public bool processing { get; set; }
        public Nullable<bool> control { get; set; }
    }
}
