create or
alter procedure dbo.process_cobra_file_table_stage_import as
begin
    
    update [dbo].[cobra_file_table_stage]
    set
        /* remove extra csv commas added to line */
        data_row = replace( data_row , ',,,,,,,,,,,,,,,,,,,,' , '' );
    
    /* upsert  into main res table*/
    MERGE dbo.cobra_file_table AS tgt
    USING (
              SELECT
                  cobra_file_name
                , data_row
                , row_num
                , row_type
                , source_row_no
                , check_type
                , error_code
                , error_message
                , error_message_calc
                , VersionNumber
                , ClientName
                , ClientDivisionName
                , Salutation
                , FirstName
                , MiddleInitial
                , LastName
                , SSN
                , IndividualID
                , Email
                , Phone
                , Phone2
                , Address1
                , Address2
                , City
                , StateOrProvince
                , PostalCode
                , Country
                , PremiumAddressSameAsPrimary
                , PremiumAddress1
                , PremiumAddress2
                , PremiumCity
                , PremiumStateOrProvince
                , PremiumPostalCode
                , PremiumCountry
                , Sex
                , DOB
                , TobaccoUse
                , EmployeeType
                , EmployeePayrollType
                , YearsOfService
                , PremiumCouponType
                , UsesHCTC
                , Active
                , AllowMemberSSO
                , BenefitGroup
                , AccountStructure
                , ClientSpecificData
                , SSOIdentifier
                , PlanCategory
                , EventType
                , EventDate
                , EnrollmentDate
                , EmployeeSSN
                , EmployeeName
                , SecondEventOriginalFDOC
                , DateSpecificRightsNoticeWasPrinted
                , PostmarkDateOfElection
                , IsPaidThroughLastDayOfCOBRA
                , NextPremiumOwedMonth
                , NextPremiumOwedYear
                , NextPremiumOwedAmountReceived
                , SendTakeoverLetter
                , IsConversionLetterSent
                , SendDODSubsidyExtension
                , PlanName
                , CoverageLevel
                , NumberOfUnit
                , StartDate
                , EndDate
                , FirstDayOfCOBRA
                , LastDayOfCOBRA
                , COBRADurationMonths
                , DaysToElect
                , DaysToMake1stPayment
                , DaysToMakeSubsequentPayments
                , ElectionPostmarkDate
                , LastDateRatesNotified
                , NumberOfUnits
                , SendPlanChangeLetterForLegacy
                , PlanBundleName
                , Relationship
                , AddressSameAsQB
                , IsQMCSO
                , UsesFDOC
                , NoteType
                , DateTime
                , NoteText
                , UserName
                , InsuranceType
                , SubsidyAmountType
                , Amount
                , SubsidyType
                , RatePeriodSubsidy
                , CASRINSERT
                , CTSRINSERT
                , MNLIFEINSERT
                , MNCONTINSERT
                , ORSRINSERT
                , TXSRINSERT
                , NYSRINSERT
                , VEBASRINSERT
                , ILSRINSERT
                , RISRINSERT
                , GASRINSERT
                , VASRINSERT
                , DisabilityApproved
                , PostmarkOfDisabilityExtension
                , DateDisabled
                , DenialReason
                , Rate
                , TermOrReinstate
                , EffectiveDate
                , Reason
                , LetterAttachmentName
                , QualifyingEventDate
                , UserDefinedFieldName
                , UserDefinedFieldValue
                , AddressSameAsSPM
                , BillingEndDate
                , BillingFrequency
                , BillingPeriodSeedDate
                , BillingStartDate
                , BillingType
                , FirstDayOfCoverage
                , FullName
                , HasWaivedAllCoverage
                , HireDate
                , InitialGracePeriodDate
                , InitialGracePeriodDays
                , Invalid
                , IsCOBRAEligible
                , IsCOBRAEligibleAtTermination
                , IsLegacy
                , LastDayOfCoverage
                , OriginalEnrollmentDate
                , SecondBillingPeriodSeedDate
                , SendGRNotice
                , SPMInitialGracePeriodOptionType
                , SPMSubsequentGracePeriodOptionType
                , SubsequentGracePeriodNrOfDays
                , UsesFamilyInAddress
                , UsesFirstDayOfCoverage
        
              from
                  dbo.cobra_file_table_stage
          ) as src
    ON (tgt.cobra_file_name = src.cobra_file_name and tgt.source_row_no = src.source_row_no)
    WHEN MATCHED THEN
        UPDATE
        SET
            cobra_file_name=src.cobra_file_name
          , data_row=src.data_row
          , row_num=src.row_num
          , row_type=src.row_type
          , source_row_no=src.source_row_no
          , check_type=src.check_type
          , error_code=src.error_code
          , error_message=src.error_message
          , error_message_calc=src.error_message_calc
          , VersionNumber=src.VersionNumber
          , ClientName=src.ClientName
          , ClientDivisionName=src.ClientDivisionName
          , Salutation=src.Salutation
          , FirstName=src.FirstName
          , MiddleInitial=src.MiddleInitial
          , LastName=src.LastName
          , SSN=src.SSN
          , IndividualID=src.IndividualID
          , Email=src.Email
          , Phone=src.Phone
          , Phone2=src.Phone2
          , Address1=src.Address1
          , Address2=src.Address2
          , City=src.City
          , StateOrProvince=src.StateOrProvince
          , PostalCode=src.PostalCode
          , Country=src.Country
          , PremiumAddressSameAsPrimary=src.PremiumAddressSameAsPrimary
          , PremiumAddress1=src.PremiumAddress1
          , PremiumAddress2=src.PremiumAddress2
          , PremiumCity=src.PremiumCity
          , PremiumStateOrProvince=src.PremiumStateOrProvince
          , PremiumPostalCode=src.PremiumPostalCode
          , PremiumCountry=src.PremiumCountry
          , Sex=src.Sex
          , DOB=src.DOB
          , TobaccoUse=src.TobaccoUse
          , EmployeeType=src.EmployeeType
          , EmployeePayrollType=src.EmployeePayrollType
          , YearsOfService=src.YearsOfService
          , PremiumCouponType=src.PremiumCouponType
          , UsesHCTC=src.UsesHCTC
          , Active=src.Active
          , AllowMemberSSO=src.AllowMemberSSO
          , BenefitGroup=src.BenefitGroup
          , AccountStructure=src.AccountStructure
          , ClientSpecificData=src.ClientSpecificData
          , SSOIdentifier=src.SSOIdentifier
          , PlanCategory=src.PlanCategory
          , EventType=src.EventType
          , EventDate=src.EventDate
          , EnrollmentDate=src.EnrollmentDate
          , EmployeeSSN=src.EmployeeSSN
          , EmployeeName=src.EmployeeName
          , SecondEventOriginalFDOC=src.SecondEventOriginalFDOC
          , DateSpecificRightsNoticeWasPrinted=src.DateSpecificRightsNoticeWasPrinted
          , PostmarkDateOfElection=src.PostmarkDateOfElection
          , IsPaidThroughLastDayOfCOBRA=src.IsPaidThroughLastDayOfCOBRA
          , NextPremiumOwedMonth=src.NextPremiumOwedMonth
          , NextPremiumOwedYear=src.NextPremiumOwedYear
          , NextPremiumOwedAmountReceived=src.NextPremiumOwedAmountReceived
          , SendTakeoverLetter=src.SendTakeoverLetter
          , IsConversionLetterSent=src.IsConversionLetterSent
          , SendDODSubsidyExtension=src.SendDODSubsidyExtension
          , PlanName=src.PlanName
          , CoverageLevel=src.CoverageLevel
          , NumberOfUnit=src.NumberOfUnit
          , StartDate=src.StartDate
          , EndDate=src.EndDate
          , FirstDayOfCOBRA=src.FirstDayOfCOBRA
          , LastDayOfCOBRA=src.LastDayOfCOBRA
          , COBRADurationMonths=src.COBRADurationMonths
          , DaysToElect=src.DaysToElect
          , DaysToMake1stPayment=src.DaysToMake1stPayment
          , DaysToMakeSubsequentPayments=src.DaysToMakeSubsequentPayments
          , ElectionPostmarkDate=src.ElectionPostmarkDate
          , LastDateRatesNotified=src.LastDateRatesNotified
          , NumberOfUnits=src.NumberOfUnits
          , SendPlanChangeLetterForLegacy=src.SendPlanChangeLetterForLegacy
          , PlanBundleName=src.PlanBundleName
          , Relationship=src.Relationship
          , AddressSameAsQB=src.AddressSameAsQB
          , IsQMCSO=src.IsQMCSO
          , UsesFDOC=src.UsesFDOC
          , NoteType=src.NoteType
          , DateTime=src.DateTime
          , NoteText=src.NoteText
          , UserName=src.UserName
          , InsuranceType=src.InsuranceType
          , SubsidyAmountType=src.SubsidyAmountType
          , Amount=src.Amount
          , SubsidyType=src.SubsidyType
          , RatePeriodSubsidy=src.RatePeriodSubsidy
          , CASRINSERT=src.CASRINSERT
          , CTSRINSERT=src.CTSRINSERT
          , MNLIFEINSERT=src.MNLIFEINSERT
          , MNCONTINSERT=src.MNCONTINSERT
          , ORSRINSERT=src.ORSRINSERT
          , TXSRINSERT=src.TXSRINSERT
          , NYSRINSERT=src.NYSRINSERT
          , VEBASRINSERT=src.VEBASRINSERT
          , ILSRINSERT=src.ILSRINSERT
          , RISRINSERT=src.RISRINSERT
          , GASRINSERT=src.GASRINSERT
          , VASRINSERT=src.VASRINSERT
          , DisabilityApproved=src.DisabilityApproved
          , PostmarkOfDisabilityExtension=src.PostmarkOfDisabilityExtension
          , DateDisabled=src.DateDisabled
          , DenialReason=src.DenialReason
          , Rate=src.Rate
          , TermOrReinstate=src.TermOrReinstate
          , EffectiveDate=src.EffectiveDate
          , Reason=src.Reason
          , LetterAttachmentName=src.LetterAttachmentName
          , QualifyingEventDate=src.QualifyingEventDate
          , UserDefinedFieldName=src.UserDefinedFieldName
          , UserDefinedFieldValue=src.UserDefinedFieldValue
          , AddressSameAsSPM=src.AddressSameAsSPM
          , BillingEndDate=src.BillingEndDate
          , BillingFrequency=src.BillingFrequency
          , BillingPeriodSeedDate=src.BillingPeriodSeedDate
          , BillingStartDate=src.BillingStartDate
          , BillingType=src.BillingType
          , FirstDayOfCoverage=src.FirstDayOfCoverage
          , FullName=src.FullName
          , HasWaivedAllCoverage=src.HasWaivedAllCoverage
          , HireDate=src.HireDate
          , InitialGracePeriodDate=src.InitialGracePeriodDate
          , InitialGracePeriodDays=src.InitialGracePeriodDays
          , Invalid=src.Invalid
          , IsCOBRAEligible=src.IsCOBRAEligible
          , IsCOBRAEligibleAtTermination=src.IsCOBRAEligibleAtTermination
          , IsLegacy=src.IsLegacy
          , LastDayOfCoverage=src.LastDayOfCoverage
          , OriginalEnrollmentDate=src.OriginalEnrollmentDate
          , SecondBillingPeriodSeedDate=src.SecondBillingPeriodSeedDate
          , SendGRNotice=src.SendGRNotice
          , SPMInitialGracePeriodOptionType=src.SPMInitialGracePeriodOptionType
          , SPMSubsequentGracePeriodOptionType=src.SPMSubsequentGracePeriodOptionType
          , SubsequentGracePeriodNrOfDays=src.SubsequentGracePeriodNrOfDays
          , UsesFamilyInAddress=src.UsesFamilyInAddress
          , UsesFirstDayOfCoverage=src.UsesFirstDayOfCoverage
    
    WHEN NOT MATCHED THEN
        INSERT (
                 cobra_file_name
               , data_row
               , row_num
               , row_type
               , source_row_no
               , check_type
               , error_code
               , error_message
               , error_message_calc
               , VersionNumber
               , ClientName
               , ClientDivisionName
               , Salutation
               , FirstName
               , MiddleInitial
               , LastName
               , SSN
               , IndividualID
               , Email
               , Phone
               , Phone2
               , Address1
               , Address2
               , City
               , StateOrProvince
               , PostalCode
               , Country
               , PremiumAddressSameAsPrimary
               , PremiumAddress1
               , PremiumAddress2
               , PremiumCity
               , PremiumStateOrProvince
               , PremiumPostalCode
               , PremiumCountry
               , Sex
               , DOB
               , TobaccoUse
               , EmployeeType
               , EmployeePayrollType
               , YearsOfService
               , PremiumCouponType
               , UsesHCTC
               , Active
               , AllowMemberSSO
               , BenefitGroup
               , AccountStructure
               , ClientSpecificData
               , SSOIdentifier
               , PlanCategory
               , EventType
               , EventDate
               , EnrollmentDate
               , EmployeeSSN
               , EmployeeName
               , SecondEventOriginalFDOC
               , DateSpecificRightsNoticeWasPrinted
               , PostmarkDateOfElection
               , IsPaidThroughLastDayOfCOBRA
               , NextPremiumOwedMonth
               , NextPremiumOwedYear
               , NextPremiumOwedAmountReceived
               , SendTakeoverLetter
               , IsConversionLetterSent
               , SendDODSubsidyExtension
               , PlanName
               , CoverageLevel
               , NumberOfUnit
               , StartDate
               , EndDate
               , FirstDayOfCOBRA
               , LastDayOfCOBRA
               , COBRADurationMonths
               , DaysToElect
               , DaysToMake1stPayment
               , DaysToMakeSubsequentPayments
               , ElectionPostmarkDate
               , LastDateRatesNotified
               , NumberOfUnits
               , SendPlanChangeLetterForLegacy
               , PlanBundleName
               , Relationship
               , AddressSameAsQB
               , IsQMCSO
               , UsesFDOC
               , NoteType
               , DateTime
               , NoteText
               , UserName
               , InsuranceType
               , SubsidyAmountType
               , Amount
               , SubsidyType
               , RatePeriodSubsidy
               , CASRINSERT
               , CTSRINSERT
               , MNLIFEINSERT
               , MNCONTINSERT
               , ORSRINSERT
               , TXSRINSERT
               , NYSRINSERT
               , VEBASRINSERT
               , ILSRINSERT
               , RISRINSERT
               , GASRINSERT
               , VASRINSERT
               , DisabilityApproved
               , PostmarkOfDisabilityExtension
               , DateDisabled
               , DenialReason
               , Rate
               , TermOrReinstate
               , EffectiveDate
               , Reason
               , LetterAttachmentName
               , QualifyingEventDate
               , UserDefinedFieldName
               , UserDefinedFieldValue
               , AddressSameAsSPM
               , BillingEndDate
               , BillingFrequency
               , BillingPeriodSeedDate
               , BillingStartDate
               , BillingType
               , FirstDayOfCoverage
               , FullName
               , HasWaivedAllCoverage
               , HireDate
               , InitialGracePeriodDate
               , InitialGracePeriodDays
               , Invalid
               , IsCOBRAEligible
               , IsCOBRAEligibleAtTermination
               , IsLegacy
               , LastDayOfCoverage
               , OriginalEnrollmentDate
               , SecondBillingPeriodSeedDate
               , SendGRNotice
               , SPMInitialGracePeriodOptionType
               , SPMSubsequentGracePeriodOptionType
               , SubsequentGracePeriodNrOfDays
               , UsesFamilyInAddress
               , UsesFirstDayOfCoverage
        
        )
        VALUES (
                   src.cobra_file_name
               ,   src.data_row
               ,   src.row_num
               ,   src.row_type
               ,   src.source_row_no
               ,   src.check_type
               ,   src.error_code
               ,   src.error_message
               ,   src.error_message_calc
               ,   src.VersionNumber
               ,   src.ClientName
               ,   src.ClientDivisionName
               ,   src.Salutation
               ,   src.FirstName
               ,   src.MiddleInitial
               ,   src.LastName
               ,   src.SSN
               ,   src.IndividualID
               ,   src.Email
               ,   src.Phone
               ,   src.Phone2
               ,   src.Address1
               ,   src.Address2
               ,   src.City
               ,   src.StateOrProvince
               ,   src.PostalCode
               ,   src.Country
               ,   src.PremiumAddressSameAsPrimary
               ,   src.PremiumAddress1
               ,   src.PremiumAddress2
               ,   src.PremiumCity
               ,   src.PremiumStateOrProvince
               ,   src.PremiumPostalCode
               ,   src.PremiumCountry
               ,   src.Sex
               ,   src.DOB
               ,   src.TobaccoUse
               ,   src.EmployeeType
               ,   src.EmployeePayrollType
               ,   src.YearsOfService
               ,   src.PremiumCouponType
               ,   src.UsesHCTC
               ,   src.Active
               ,   src.AllowMemberSSO
               ,   src.BenefitGroup
               ,   src.AccountStructure
               ,   src.ClientSpecificData
               ,   src.SSOIdentifier
               ,   src.PlanCategory
               ,   src.EventType
               ,   src.EventDate
               ,   src.EnrollmentDate
               ,   src.EmployeeSSN
               ,   src.EmployeeName
               ,   src.SecondEventOriginalFDOC
               ,   src.DateSpecificRightsNoticeWasPrinted
               ,   src.PostmarkDateOfElection
               ,   src.IsPaidThroughLastDayOfCOBRA
               ,   src.NextPremiumOwedMonth
               ,   src.NextPremiumOwedYear
               ,   src.NextPremiumOwedAmountReceived
               ,   src.SendTakeoverLetter
               ,   src.IsConversionLetterSent
               ,   src.SendDODSubsidyExtension
               ,   src.PlanName
               ,   src.CoverageLevel
               ,   src.NumberOfUnit
               ,   src.StartDate
               ,   src.EndDate
               ,   src.FirstDayOfCOBRA
               ,   src.LastDayOfCOBRA
               ,   src.COBRADurationMonths
               ,   src.DaysToElect
               ,   src.DaysToMake1stPayment
               ,   src.DaysToMakeSubsequentPayments
               ,   src.ElectionPostmarkDate
               ,   src.LastDateRatesNotified
               ,   src.NumberOfUnits
               ,   src.SendPlanChangeLetterForLegacy
               ,   src.PlanBundleName
               ,   src.Relationship
               ,   src.AddressSameAsQB
               ,   src.IsQMCSO
               ,   src.UsesFDOC
               ,   src.NoteType
               ,   src.DateTime
               ,   src.NoteText
               ,   src.UserName
               ,   src.InsuranceType
               ,   src.SubsidyAmountType
               ,   src.Amount
               ,   src.SubsidyType
               ,   src.RatePeriodSubsidy
               ,   src.CASRINSERT
               ,   src.CTSRINSERT
               ,   src.MNLIFEINSERT
               ,   src.MNCONTINSERT
               ,   src.ORSRINSERT
               ,   src.TXSRINSERT
               ,   src.NYSRINSERT
               ,   src.VEBASRINSERT
               ,   src.ILSRINSERT
               ,   src.RISRINSERT
               ,   src.GASRINSERT
               ,   src.VASRINSERT
               ,   src.DisabilityApproved
               ,   src.PostmarkOfDisabilityExtension
               ,   src.DateDisabled
               ,   src.DenialReason
               ,   src.Rate
               ,   src.TermOrReinstate
               ,   src.EffectiveDate
               ,   src.Reason
               ,   src.LetterAttachmentName
               ,   src.QualifyingEventDate
               ,   src.UserDefinedFieldName
               ,   src.UserDefinedFieldValue
               ,   src.AddressSameAsSPM
               ,   src.BillingEndDate
               ,   src.BillingFrequency
               ,   src.BillingPeriodSeedDate
               ,   src.BillingStartDate
               ,   src.BillingType
               ,   src.FirstDayOfCoverage
               ,   src.FullName
               ,   src.HasWaivedAllCoverage
               ,   src.HireDate
               ,   src.InitialGracePeriodDate
               ,   src.InitialGracePeriodDays
               ,   src.Invalid
               ,   src.IsCOBRAEligible
               ,   src.IsCOBRAEligibleAtTermination
               ,   src.IsLegacy
               ,   src.LastDayOfCoverage
               ,   src.OriginalEnrollmentDate
               ,   src.SecondBillingPeriodSeedDate
               ,   src.SendGRNotice
               ,   src.SPMInitialGracePeriodOptionType
               ,   src.SPMSubsequentGracePeriodOptionType
               ,   src.SubsequentGracePeriodNrOfDays
               ,   src.UsesFamilyInAddress
               ,   src.UsesFirstDayOfCoverage
               );
    
    --    truncate table [dbo].[cobra_file_table_stage];
end
go

