//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.COBRA
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBRA_FRC
    {
        public int MemberID { get; set; }
        public string first { get; set; }
        public string last { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> BillingStartDate { get; set; }
        public string BillingFrequency { get; set; }
        public string enrolled_plans { get; set; }
        public string coverage_level { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> premium_date { get; set; }
        public Nullable<decimal> MemberOwes { get; set; }
        public Nullable<decimal> Expr3 { get; set; }
        public string BillingType { get; set; }
        public string account_type { get; set; }
        public string RateType { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string AmountType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Expr2 { get; set; }
    }
}
