//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.COBRA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class COBRAEntities : DbContext
    {
        public COBRAEntities()
            : base("name=COBRAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COBRA_FRC> COBRA_FRC { get; set; }
        public virtual DbSet<COBRA_QB_demo> COBRA_QB_demo { get; set; }
        public virtual DbSet<COBRA_QB_plans> COBRA_QB_plans { get; set; }
    
        public virtual int Fix_COBRA_brokerage_Contacts_SSObollean()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Fix_COBRA_brokerage_Contacts_SSObollean");
        }
    
        public virtual int Fix_COBRA_Client_Contacts_SSObollean()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Fix_COBRA_Client_Contacts_SSObollean");
        }
    
        public virtual int Fix_COBRAQB_SSObollean()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Fix_COBRAQB_SSObollean");
        }
    
        public virtual int Get_COBRA_QBs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Get_COBRA_QBs");
        }
    }
}
