//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.COBRA
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBRA_QB_demo
    {
        public int MemberID { get; set; }
        public bool Active { get; set; }
        public string ClientName { get; set; }
        public string DivisionName { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string Salutation { get; set; }
        public string SSN { get; set; }
        public string IndividualIdentifier { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string TobaccoUse { get; set; }
        public string EmployeeType { get; set; }
        public string PayrollType { get; set; }
        public Nullable<int> YearsOfService { get; set; }
        public string PremiumCouponType { get; set; }
        public bool UsesHCTC { get; set; }
        public Nullable<System.DateTime> EnteredDateTime { get; set; }
        public string EnteredByUser { get; set; }
        public string MethodEntered { get; set; }
        public Nullable<System.DateTime> PaidThroughDate { get; set; }
        public Nullable<System.DateTime> OnlineElectionProcessedDate { get; set; }
        public string BenefitGroup { get; set; }
        public string AccountStructure { get; set; }
        public string ClientCustomData { get; set; }
        public Nullable<bool> AllowSSO { get; set; }
        public string SSOIdentifier { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
