//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.Cobra
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerContact
    {
        public int BrokerContactID { get; set; }
        public int BrokerID { get; set; }
        public string ContactType { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string Department { get; set; }
        public string Phone { get; set; }
        public string PhoneExtension { get; set; }
        public string Phone2 { get; set; }
        public string Phone2Extension { get; set; }
        public string Fax { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public Nullable<int> Active { get; set; }
        public string LoginStatus { get; set; }
        public string RegistrationCode { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string UserDisplayName { get; set; }
        public Nullable<int> AllowSSO { get; set; }
        public string SSOIdentifier { get; set; }
    }
}
