//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.AlegeusFileProcessing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Alegeus_File_ProcessingEntities : DbContext
    {
        public Alegeus_File_ProcessingEntities()
            : base("name=Alegeus_File_ProcessingEntitiesPROD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alegeus_file_staging> alegeus_file_staging { get; set; }
        public virtual DbSet<Automated_Header_list> Automated_Header_list { get; set; }
    
        public virtual int Alegeus_Header_n_success()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Alegeus_Header_n_success");
        }
    
        public virtual int build_auto_ftp_batfile()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("build_auto_ftp_batfile");
        }
    
        public virtual int insert_to_auto_ftp_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_to_auto_ftp_list");
        }
    
        public virtual ObjectResult<string> proc_alegeus_AlterHeaders2015()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_alegeus_AlterHeaders2015");
        }
    
        public virtual ObjectResult<string> proc_alegeus_AlterHeaders2019()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_alegeus_AlterHeaders2019");
        }
    
        public virtual ObjectResult<proc_alegeus_AlterHeadersNone_Result> proc_alegeus_AlterHeadersNone()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_alegeus_AlterHeadersNone_Result>("proc_alegeus_AlterHeadersNone");
        }
    }
}
