//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.AlegeusErrorLog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Alegeus_ErrorLogEntities : DbContext
    {
        public Alegeus_ErrorLogEntities()
            : base("name=Alegeus_ErrorLogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dbo_error_log_results_workflow_local> dbo_error_log_results_workflow_local { get; set; }
        public virtual DbSet<dbo_error_log_results_workflow_local_AL> dbo_error_log_results_workflow_local_AL { get; set; }
        public virtual DbSet<dbo_error_log_results_workflow_localBU> dbo_error_log_results_workflow_localBU { get; set; }
        public virtual DbSet<dbo_tracked_errors_local> dbo_tracked_errors_local { get; set; }
        public virtual DbSet<mbi_file_table> mbi_file_table { get; set; }
        public virtual DbSet<mbi_file_table_stage> mbi_file_table_stage { get; set; }
        public virtual DbSet<mbi_file_table_stage_prv> mbi_file_table_stage_prv { get; set; }
        public virtual DbSet<res_file_table> res_file_table { get; set; }
        public virtual DbSet<res_file_table_stage> res_file_table_stage { get; set; }
    
        [DbFunction("Alegeus_ErrorLogEntities", "CsvSplit1")]
        public virtual IQueryable<CsvSplit1_Result> CsvSplit1(string delimited, string delimiter)
        {
            var delimitedParameter = delimited != null ?
                new ObjectParameter("delimited", delimited) :
                new ObjectParameter("delimited", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("delimiter", delimiter) :
                new ObjectParameter("delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CsvSplit1_Result>("[Alegeus_ErrorLogEntities].[CsvSplit1](@delimited, @delimiter)", delimitedParameter, delimiterParameter);
        }
    
        [DbFunction("Alegeus_ErrorLogEntities", "SplitErrorRowStringToFields")]
        public virtual IQueryable<SplitErrorRowStringToFields_Result> SplitErrorRowStringToFields(string csvString)
        {
            var csvStringParameter = csvString != null ?
                new ObjectParameter("csvString", csvString) :
                new ObjectParameter("csvString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitErrorRowStringToFields_Result>("[Alegeus_ErrorLogEntities].[SplitErrorRowStringToFields](@csvString)", csvStringParameter);
        }
    
        [DbFunction("Alegeus_ErrorLogEntities", "SplitStringsOrdered")]
        public virtual IQueryable<SplitStringsOrdered_Result> SplitStringsOrdered(string list, string delimiter)
        {
            var listParameter = list != null ?
                new ObjectParameter("List", list) :
                new ObjectParameter("List", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitStringsOrdered_Result>("[Alegeus_ErrorLogEntities].[SplitStringsOrdered](@List, @Delimiter)", listParameter, delimiterParameter);
        }
    
        public virtual int Alegeus_ErrorLog_failure_alert()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Alegeus_ErrorLog_failure_alert");
        }
    
        public virtual int Alegeus_ErrorLog_refreshsuccess_alert()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Alegeus_ErrorLog_refreshsuccess_alert");
        }
    
        public virtual int alegeus_errorlog_track_new_ftp_errors()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("alegeus_errorlog_track_new_ftp_errors");
        }
    
        public virtual ObjectResult<Nullable<int>> check_imports_file()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("check_imports_file");
        }
    
        public virtual int process_mbi_file_table_stage_import()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("process_mbi_file_table_stage_import");
        }
    
        public virtual int process_res_file_table_stage_import()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("process_res_file_table_stage_import");
        }
    
        public virtual int SplitAllErrorRowStringsToFields(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SplitAllErrorRowStringsToFields", tableNameParameter);
        }
    
        public virtual int zz_truncate_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zz_truncate_all");
        }
    }
}
