//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.AlegeusErrorLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class mbi_file_table_stage
    {
        public string mbi_file_name { get; set; }
        public string data_row { get; set; }
        public int row_num { get; set; }
        public string row_type { get; set; }
        public string AccountStatus { get; set; }
        public string AccountTypeCode { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string BirthDate { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string DeleteAccount { get; set; }
        public string DependentID { get; set; }
        public string DepositType { get; set; }
        public string Division { get; set; }
        public string EffectiveDate { get; set; }
        public string EligibilityDate { get; set; }
        public string Email { get; set; }
        public string EmployeeDepositAmount { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeePayPeriodElection { get; set; }
        public string EmployeeSocialSecurityNumber { get; set; }
        public string EmployeeStatus { get; set; }
        public string EmployerDepositAmount { get; set; }
        public string EmployerId { get; set; }
        public string EmployerPayPeriodElection { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleInitial { get; set; }
        public string MobileNumber { get; set; }
        public string OriginalPrefunded { get; set; }
        public string Phone { get; set; }
        public string PlanEndDate { get; set; }
        public string PlanId { get; set; }
        public string PlanStartDate { get; set; }
        public string Relationship { get; set; }
        public string State { get; set; }
        public string TerminationDate { get; set; }
        public string TpaId { get; set; }
        public string Zip { get; set; }
        public Nullable<int> source_row_no { get; set; }
        public string check_type { get; set; }
        public string error_code { get; set; }
        public string error_message { get; set; }
        public string error_message_calc { get; set; }
    }
}
