//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.DataProcessing
{
    using System;
    using System.Collections.Generic;
    
    public partial class alegeus_file_staging
    {
        public string data_row { get; set; }
        public string folder_name { get; set; }
        public int row_num { get; set; }
    }
}
