//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.AlegeusFileProcessing
{
    using System;
    using System.Collections.Generic;
    
    public partial class message_log
    {
        public int log_id { get; set; }
        public string module_name { get; set; }
        public string submodule_name { get; set; }
        public string step_type { get; set; }
        public string step_name { get; set; }
        public string command { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
