//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.DataProcessing
{
    using System;
    using System.Collections.Generic;
    
    public partial class cobra_res_file_table_stage
    {
        public string result_template { get; set; }
        public string error_row { get; set; }
        public string error_code { get; set; }
        public string error_message { get; set; }
        public int row_num { get; set; }
        public string row_type { get; set; }
        public string error_message_calc { get; set; }
        public string cobra_res_file_name { get; set; }
        public string data_row { get; set; }
        public Nullable<int> source_row_no { get; set; }
        public string check_type { get; set; }
        public string VersionNumber { get; set; }
        public string ClientName { get; set; }
        public string ClientDivisionName { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string SSN { get; set; }
        public string IndividualID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateOrProvince { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string PremiumAddressSameAsPrimary { get; set; }
        public string PremiumAddress1 { get; set; }
        public string PremiumAddress2 { get; set; }
        public string PremiumCity { get; set; }
        public string PremiumStateOrProvince { get; set; }
        public string PremiumPostalCode { get; set; }
        public string PremiumCountry { get; set; }
        public string Sex { get; set; }
        public string DOB { get; set; }
        public string TobaccoUse { get; set; }
        public string EmployeeType { get; set; }
        public string EmployeePayrollType { get; set; }
        public string YearsOfService { get; set; }
        public string PremiumCouponType { get; set; }
        public string UsesHCTC { get; set; }
        public string Active { get; set; }
        public string AllowMemberSSO { get; set; }
        public string BenefitGroup { get; set; }
        public string AccountStructure { get; set; }
        public string ClientSpecificData { get; set; }
        public string SSOIdentifier { get; set; }
        public string PlanCategory { get; set; }
        public string EventType { get; set; }
        public string EventDate { get; set; }
        public string EnrollmentDate { get; set; }
        public string EmployeeSSN { get; set; }
        public string EmployeeName { get; set; }
        public string SecondEventOriginalFDOC { get; set; }
        public string DateSpecificRightsNoticeWasPrinted { get; set; }
        public string PostmarkDateOfElection { get; set; }
        public string IsPaidThroughLastDayOfCOBRA { get; set; }
        public string NextPremiumOwedMonth { get; set; }
        public string NextPremiumOwedYear { get; set; }
        public string NextPremiumOwedAmountReceived { get; set; }
        public string SendTakeoverLetter { get; set; }
        public string IsConversionLetterSent { get; set; }
        public string SendDODSubsidyExtension { get; set; }
        public string PlanName { get; set; }
        public string CoverageLevel { get; set; }
        public string NumberOfUnit { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string FirstDayOfCOBRA { get; set; }
        public string LastDayOfCOBRA { get; set; }
        public string COBRADurationMonths { get; set; }
        public string DaysToElect { get; set; }
        public string DaysToMake1stPayment { get; set; }
        public string DaysToMakeSubsequentPayments { get; set; }
        public string ElectionPostmarkDate { get; set; }
        public string LastDateRatesNotified { get; set; }
        public string NumberOfUnits { get; set; }
        public string SendPlanChangeLetterForLegacy { get; set; }
        public string PlanBundleName { get; set; }
        public string Relationship { get; set; }
        public string AddressSameAsQB { get; set; }
        public string IsQMCSO { get; set; }
        public string UsesFDOC { get; set; }
        public string NoteType { get; set; }
        public string DateTime { get; set; }
        public string NoteText { get; set; }
        public string UserName { get; set; }
        public string InsuranceType { get; set; }
        public string SubsidyAmountType { get; set; }
        public string Amount { get; set; }
        public string SubsidyType { get; set; }
        public string RatePeriodSubsidy { get; set; }
        public string CASRINSERT { get; set; }
        public string CTSRINSERT { get; set; }
        public string MNLIFEINSERT { get; set; }
        public string MNCONTINSERT { get; set; }
        public string ORSRINSERT { get; set; }
        public string TXSRINSERT { get; set; }
        public string NYSRINSERT { get; set; }
        public string VEBASRINSERT { get; set; }
        public string ILSRINSERT { get; set; }
        public string RISRINSERT { get; set; }
        public string GASRINSERT { get; set; }
        public string VASRINSERT { get; set; }
        public string DisabilityApproved { get; set; }
        public string PostmarkOfDisabilityExtension { get; set; }
        public string DateDisabled { get; set; }
        public string DenialReason { get; set; }
        public string Rate { get; set; }
        public string TermOrReinstate { get; set; }
        public string EffectiveDate { get; set; }
        public string Reason { get; set; }
        public string LetterAttachmentName { get; set; }
        public string QualifyingEventDate { get; set; }
        public string UserDefinedFieldName { get; set; }
        public string UserDefinedFieldValue { get; set; }
    }
}
