//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.DataProcessing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header_list_old
    {
        public string Folder_name { get; set; }
        public string template_type { get; set; }
        public string IC_type { get; set; }
        public int ID { get; set; }
        public string to_FTP { get; set; }
        public string BENCODE { get; set; }
        public string environment { get; set; }
    }
}
