//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUserRole
    {
        public int AdminUserRoleID { get; set; }
        public System.Guid User { get; set; }
        public string AdminRoleID { get; set; }
    
        public virtual AdminRole AdminRole { get; set; }
        public virtual AdminUser AdminUser { get; set; }
    }
}
