//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminDashboard
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Month { get; set; }
        public string MonthLetter { get; set; }
        public string MonthAbbreviation { get; set; }
        public int MemberTotal { get; set; }
        public int QBTotal { get; set; }
        public int QBsAdded { get; set; }
        public int QBsDeleted { get; set; }
        public int QBsPendingAndEnrolled { get; set; }
        public int QBsTermed { get; set; }
        public int SPMTotal { get; set; }
        public int SPMsAdded { get; set; }
        public int SPMsDeleted { get; set; }
        public Nullable<int> SPMsPendingAndEnrolled { get; set; }
        public int SPMsTermed { get; set; }
        public int NPMTotal { get; set; }
        public int NPMsAdded { get; set; }
        public int NPMsDeleted { get; set; }
        public int LettersProcessed { get; set; }
        public int ClientTotal { get; set; }
        public int ClientsAdded { get; set; }
        public int ClientsDeleted { get; set; }
        public int ClientDivisionTotal { get; set; }
        public int ClientDivisionsAdded { get; set; }
        public int ClientDivisionsDeleted { get; set; }
        public int ClientGroupTotal { get; set; }
        public int ClientGroupsAdded { get; set; }
        public int ClientGroupsDeleted { get; set; }
        public int CarrierTotal { get; set; }
        public int CarriersAdded { get; set; }
        public int CarriersDeleted { get; set; }
        public int NumberOfPayments { get; set; }
        public decimal DepositTotal { get; set; }
        public int NumberOfVoidedPayments { get; set; }
        public decimal VoidedPaymentTotal { get; set; }
        public int NumberOfRemittedPayments { get; set; }
        public decimal RemittedTotal { get; set; }
        public int NumberOfRefunds { get; set; }
        public decimal RefundTotal { get; set; }
        public int NumberOfBookedAdminFees { get; set; }
        public decimal BookedAdminFeesTotal { get; set; }
        public decimal CashBalance { get; set; }
    }
}
