//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllClientsAndDivision
    {
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public int ClientGroupID { get; set; }
        public string DBAName { get; set; }
        public string EIN { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> BillingStartDate { get; set; }
        public Nullable<bool> SendHIPAACertWithQBSRandQBTermination { get; set; }
        public Nullable<bool> SendHIPAACertWithWelcomeLetter { get; set; }
        public Nullable<bool> AllowClientPortalAccess { get; set; }
        public Nullable<bool> AutomaticallyCreateQBSubsidyForInsignificantAmount { get; set; }
        public Nullable<bool> IgnoreSPMPaymentGracePeriods { get; set; }
        public Nullable<bool> MigratedClient { get; set; }
        public string ClientPremiumNotice { get; set; }
        public string EmployeeCountRange { get; set; }
        public string WeeklyBillingFirstDayOfWeek { get; set; }
        public Nullable<bool> ClientRequiresAEI2009SubsidyEligibleAttestationToSubsidize { get; set; }
        public Nullable<bool> ClientAllowsAEI2009PlanEnrollmentOptions { get; set; }
        public Nullable<bool> ClientDoesOwnAEI2009SubsidyTakenReportPosting { get; set; }
        public string ClientAlternate { get; set; }
        public Nullable<bool> AllowClientSSO { get; set; }
        public Nullable<int> SPMInitialGracePeriodDays { get; set; }
        public Nullable<decimal> SPMConvenienceFee { get; set; }
        public Nullable<decimal> SPMPartnerConvenienceFee { get; set; }
        public Nullable<decimal> QBConvenienceFee { get; set; }
        public Nullable<decimal> QBPartnerConvenienceFee { get; set; }
        public Nullable<int> ClientDivisionID { get; set; }
        public string DivisionName { get; set; }
        public string DivisionAddress1 { get; set; }
        public string DivisionAddress2 { get; set; }
        public string DivisionCity { get; set; }
        public string DivisionState { get; set; }
        public string DivisionPostalCode { get; set; }
        public string DivisionCountry { get; set; }
        public string DivisionPhone { get; set; }
        public string DivisionFaxc { get; set; }
        public Nullable<bool> ClientDivisionDoesOwnAEI2009SubsidyTakenReportPosting { get; set; }
        public Nullable<bool> DivisionSendHIPAACert { get; set; }
        public Nullable<bool> AllowClientDivisionSSO { get; set; }
        public Nullable<bool> DivisionActive { get; set; }
    }
}
