//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllSSOUser
    {
        public int orderseq { get; set; }
        public string entitytype { get; set; }
        public Nullable<int> memberid { get; set; }
        public Nullable<int> brokerid { get; set; }
        public Nullable<int> clientcontactid { get; set; }
        public Nullable<int> clientid { get; set; }
        public Nullable<int> clientdivisionid { get; set; }
        public string organizationname { get; set; }
        public Nullable<int> organizationisactive { get; set; }
        public string divisionname { get; set; }
        public string individualidentifier { get; set; }
        public string contacttype { get; set; }
        public string salutation { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string title { get; set; }
        public string department { get; set; }
        public string phone { get; set; }
        public string phone2 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postalcode { get; set; }
        public string country { get; set; }
        public Nullable<int> active { get; set; }
        public string loginstatus { get; set; }
        public string registrationcode { get; set; }
        public Nullable<System.DateTime> registrationdate { get; set; }
        public string userdisplayname { get; set; }
        public Nullable<int> allowsso { get; set; }
        public string ssoidentifier { get; set; }
        public string userid { get; set; }
        public string ssn { get; set; }
        public string employeeid { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string employerid { get; set; }
        public Nullable<System.DateTime> QualEventDate { get; set; }
    }
}
