//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerNote
    {
        public int BrokerNoteID { get; set; }
        public int BrokerID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string NoteText { get; set; }
        public string NoteType { get; set; }
        public System.Guid User { get; set; }
    }
}
