//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrierContact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarrierContact()
        {
            this.ClientPlanQBs = new HashSet<ClientPlanQB>();
            this.ClientPlanQBs1 = new HashSet<ClientPlanQB>();
            this.ClientPlanQBs2 = new HashSet<ClientPlanQB>();
            this.ClientPlanQBEmailLists = new HashSet<ClientPlanQBEmailList>();
            this.ClientPlanSPMs = new HashSet<ClientPlanSPM>();
            this.ClientPlanSPMs1 = new HashSet<ClientPlanSPM>();
            this.ClientPlanSPMs2 = new HashSet<ClientPlanSPM>();
            this.ClientPlanSPMEmailLists = new HashSet<ClientPlanSPMEmailList>();
        }
    
        public int CarrierContactID { get; set; }
        public int CarrierID { get; set; }
        public string ContactType { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string Department { get; set; }
        public string Phone { get; set; }
        public string PhoneExtension { get; set; }
        public string Phone2 { get; set; }
        public string Phone2Extension { get; set; }
        public string Fax { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string WebLink { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> RemitViaACH { get; set; }
        public string RemittanceACHAccountType { get; set; }
    
        public virtual Carrier Carrier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPlanQB> ClientPlanQBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPlanQB> ClientPlanQBs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPlanQB> ClientPlanQBs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPlanQBEmailList> ClientPlanQBEmailLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPlanSPM> ClientPlanSPMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPlanSPM> ClientPlanSPMs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPlanSPM> ClientPlanSPMs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPlanSPMEmailList> ClientPlanSPMEmailLists { get; set; }
    }
}
