//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPlanQB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientPlanQB()
        {
            this.ClientDivisionQBPlans = new HashSet<ClientDivisionQBPlan>();
            this.ClientPlanQBBundles = new HashSet<ClientPlanQBBundle>();
            this.ClientPlanQBCarrierSubcodes = new HashSet<ClientPlanQBCarrierSubcode>();
            this.ClientPlanQBEmailLists = new HashSet<ClientPlanQBEmailList>();
            this.ClientPlanQBNotes = new HashSet<ClientPlanQBNote>();
            this.ClientPlanQBRates = new HashSet<ClientPlanQBRate>();
            this.QBDependentPlans = new HashSet<QBDependentPlan>();
            this.QBPlans = new HashSet<QBPlan>();
            this.QBPlanCarrierSubcodes = new HashSet<QBPlanCarrierSubcode>();
        }
    
        public int ClientPlanQBID { get; set; }
        public int ClientID { get; set; }
        public string PlanName { get; set; }
        public string CarrierPlanIdentification { get; set; }
        public string InsuranceType { get; set; }
        public string RateType { get; set; }
        public Nullable<int> CarrierID { get; set; }
        public Nullable<int> CarrierEnrollmentContactID { get; set; }
        public Nullable<int> CarrierCustomerServiceContactID { get; set; }
        public Nullable<int> CarrierRemittanceContactID { get; set; }
        public string BenefitTerminationType { get; set; }
        public string InsuredType { get; set; }
        public Nullable<int> WaitingPeriod { get; set; }
        public Nullable<int> FSARenewalMonth { get; set; }
        public string AgeDeterminedBy { get; set; }
        public Nullable<bool> ConversionToIndividualPlansAllowed { get; set; }
        public Nullable<bool> MonthlyUpdateRequired { get; set; }
        public Nullable<bool> UseCoverageLevelNameForQB { get; set; }
        public Nullable<bool> IsCarrierRemit { get; set; }
        public Nullable<bool> AEI2009PlanEnrollmentOption { get; set; }
        public Nullable<bool> AdjustWithCarrier { get; set; }
        public Nullable<bool> SuppressCarrierNotificationDelivery { get; set; }
        public Nullable<System.DateTime> PlanYearStartDate { get; set; }
        public Nullable<System.DateTime> PlanYearEndDate { get; set; }
        public string PlanCategory { get; set; }
    
        public virtual Carrier Carrier { get; set; }
        public virtual CarrierContact CarrierContact { get; set; }
        public virtual CarrierContact CarrierContact1 { get; set; }
        public virtual CarrierContact CarrierContact2 { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientDivisionQBPlan> ClientDivisionQBPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPlanQBBundle> ClientPlanQBBundles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPlanQBCarrierSubcode> ClientPlanQBCarrierSubcodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPlanQBEmailList> ClientPlanQBEmailLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPlanQBNote> ClientPlanQBNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPlanQBRate> ClientPlanQBRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QBDependentPlan> QBDependentPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QBPlan> QBPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QBPlanCarrierSubcode> QBPlanCarrierSubcodes { get; set; }
    }
}
