//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPlanSPMEmailList
    {
        public int ClientPlanSPMEmailListID { get; set; }
        public int ClientPlanSPMID { get; set; }
        public string ContactType { get; set; }
        public Nullable<int> CarrierContactID { get; set; }
        public Nullable<int> ClientContactID { get; set; }
    
        public virtual CarrierContact CarrierContact { get; set; }
        public virtual ClientPlanSPM ClientPlanSPM { get; set; }
    }
}
