//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDivision
    {
        public int ClientDivisionID { get; set; }
        public int ClientID { get; set; }
        public string DivisionName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<int> ClientDivisionDoesOwnAEI2009SubsidyTakenReportPosting { get; set; }
        public Nullable<int> SendHIPAACertWithSPMWelcomeAndTerminationLetters { get; set; }
        public Nullable<int> AllowClientDivisionSSO { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
