//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProcess
    {
        public int ClientProcessID { get; set; }
        public bool SuppressQBCarrierNotificationDelivery { get; set; }
        public bool SuppressSPMCarrierNotificationDelivery { get; set; }
        public Nullable<System.DateTime> ClientDeactivationDate { get; set; }
        public int ClientID { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
