//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPlanSPMBundle
    {
        public int ID { get; set; }
        public int ClientPlanSPMBundleID { get; set; }
        public int ClientPlanSPMID { get; set; }
        public int ClientID { get; set; }
        public string BundleName { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ClientPlanSPM ClientPlanSPM { get; set; }
    }
}
