//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientFee
    {
        public int ClientFeeID { get; set; }
        public int ClientID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ClientInvoiceType { get; set; }
        public Nullable<decimal> PEPMRateAmount { get; set; }
        public Nullable<decimal> PEPMMinimumBillAmount { get; set; }
        public Nullable<decimal> POMinimumBillAmount { get; set; }
        public Nullable<decimal> POQEAmount { get; set; }
        public Nullable<decimal> POHIPAAAmount { get; set; }
        public Nullable<decimal> POGeneralNoticeAmount { get; set; }
        public Nullable<decimal> SetupFee { get; set; }
        public Nullable<decimal> SPMBillingFee { get; set; }
        public Nullable<bool> ClientPaysAdminFee { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
