//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDivisionSPMPlanBundle
    {
        public int ClientDivisionSPMPlanBundleID { get; set; }
        public int ClientDivisionID { get; set; }
        public Nullable<int> ClientPlanSPMBundleID { get; set; }
        public bool Selected { get; set; }
    
        public virtual ClientDivision ClientDivision { get; set; }
    }
}
