//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPlanQBRank
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string InsuranceType { get; set; }
        public int Priority { get; set; }
        public bool IsManuallyEntered { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
