//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CobraPointEntities : DbContext
    {
        public CobraPointEntities()
            : base("name=CobraPointEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<db_error_log> db_error_log { get; set; }
        public virtual DbSet<db_message_log> db_message_log { get; set; }
        public virtual DbSet<QBAEI_ClientList_csv> QBAEI_ClientList_csv { get; set; }
        public virtual DbSet<AdminTPAUser> AdminTPAUsers { get; set; }
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<AllClientsAndDivision> AllClientsAndDivisions { get; set; }
        public virtual DbSet<AllSSOUser> AllSSOUsers { get; set; }
        public virtual DbSet<Broker> Brokers { get; set; }
        public virtual DbSet<BrokerClient> BrokerClients { get; set; }
        public virtual DbSet<BrokerContact> BrokerContacts { get; set; }
        public virtual DbSet<Carrier> Carriers { get; set; }
        public virtual DbSet<CarrierContact> CarrierContacts { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientContact> ClientContacts { get; set; }
        public virtual DbSet<ClientDivision> ClientDivisions { get; set; }
        public virtual DbSet<ClientDivisionContact> ClientDivisionContacts { get; set; }
        public virtual DbSet<NPM> NPMs { get; set; }
        public virtual DbSet<QB> QBs { get; set; }
        public virtual DbSet<QBEvent> QBEvents { get; set; }
        public virtual DbSet<QBPlan> QBPlans { get; set; }
        public virtual DbSet<SPM> SPMs { get; set; }
        public virtual DbSet<SPMAccess> SPMAccesses { get; set; }
    
        public virtual ObjectResult<string> COBRA_Update_alert()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("COBRA_Update_alert");
        }
    
        public virtual int db_log_error(string err_no, string err_source, string err_msg, string sqlstate)
        {
            var err_noParameter = err_no != null ?
                new ObjectParameter("err_no", err_no) :
                new ObjectParameter("err_no", typeof(string));
    
            var err_sourceParameter = err_source != null ?
                new ObjectParameter("err_source", err_source) :
                new ObjectParameter("err_source", typeof(string));
    
            var err_msgParameter = err_msg != null ?
                new ObjectParameter("err_msg", err_msg) :
                new ObjectParameter("err_msg", typeof(string));
    
            var sqlstateParameter = sqlstate != null ?
                new ObjectParameter("sqlstate", sqlstate) :
                new ObjectParameter("sqlstate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("db_log_error", err_noParameter, err_sourceParameter, err_msgParameter, sqlstateParameter);
        }
    
        public virtual int db_log_message(string msg_source, string msg, string log_level, Nullable<int> recsaffected)
        {
            var msg_sourceParameter = msg_source != null ?
                new ObjectParameter("msg_source", msg_source) :
                new ObjectParameter("msg_source", typeof(string));
    
            var msgParameter = msg != null ?
                new ObjectParameter("msg", msg) :
                new ObjectParameter("msg", typeof(string));
    
            var log_levelParameter = log_level != null ?
                new ObjectParameter("log_level", log_level) :
                new ObjectParameter("log_level", typeof(string));
    
            var recsaffectedParameter = recsaffected.HasValue ?
                new ObjectParameter("recsaffected", recsaffected) :
                new ObjectParameter("recsaffected", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("db_log_message", msg_sourceParameter, msgParameter, log_levelParameter, recsaffectedParameter);
        }
    
        public virtual int exp_cp_AllSSOUsers_to_Portal(string p_only_for_email)
        {
            var p_only_for_emailParameter = p_only_for_email != null ?
                new ObjectParameter("p_only_for_email", p_only_for_email) :
                new ObjectParameter("p_only_for_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("exp_cp_AllSSOUsers_to_Portal", p_only_for_emailParameter);
        }
    
        public virtual int exp_cp_AllSSOUsers_to_Portal_PRV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("exp_cp_AllSSOUsers_to_Portal_PRV");
        }
    
        public virtual int export_cp_tables_to_portal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("export_cp_tables_to_portal");
        }
    
        public virtual int QBAEI_Create_filesandInsertintoRunLog()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QBAEI_Create_filesandInsertintoRunLog");
        }
    
        public virtual int QBAEI_Create_filesandInsertintoRunLog_notunknown()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("QBAEI_Create_filesandInsertintoRunLog_notunknown");
        }
    }
}
