//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public int LoginLogID { get; set; }
        public Nullable<System.Guid> User { get; set; }
        public Nullable<System.DateTime> LoginDateTime { get; set; }
        public string PortalType { get; set; }
        public string HostAddress { get; set; }
        public string BrowserName { get; set; }
        public string BrowserVersion { get; set; }
        public string UrlReferrer { get; set; }
    }
}
