//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberLetterAttachment
    {
        public int MemberID { get; set; }
        public Nullable<int> LetterAttachmentID { get; set; }
        public Nullable<int> LetterTypeID { get; set; }
        public string EntityName { get; set; }
    
        public virtual LetterAttachment LetterAttachment { get; set; }
        public virtual LetterType LetterType { get; set; }
    }
}
