//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPM
    {
        public int MemberID { get; set; }
        public int ClientDivisionID { get; set; }
        public Nullable<int> Active { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string MethodEntered { get; set; }
        public string EnteredByUser { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string IndividualID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public Nullable<int> UsesAndFamily { get; set; }
        public Nullable<int> HasBecomeAQB { get; set; }
        public Nullable<int> HasWaivedAllCoverage { get; set; }
        public string HireDate { get; set; }
        public Nullable<int> IsGRLetterSent { get; set; }
        public string EnteredDateTime { get; set; }
        public string LastModifiedDate { get; set; }
        public string SSN { get; set; }
    }
}
