//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPMHIPAACertDataDependent
    {
        public int NPMHIPAACertDataDependentID { get; set; }
        public int NPMHIPAACertDataID { get; set; }
        public string FullName { get; set; }
        public string Relationship { get; set; }
        public Nullable<System.DateTime> OriginalEnrollmentDate { get; set; }
        public Nullable<System.DateTime> LastDayOfCoverage { get; set; }
        public Nullable<System.DateTime> EnteredDatetime { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual NPMHIPAACertData NPMHIPAACertData { get; set; }
    }
}
