//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPMHIPAACertData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NPMHIPAACertData()
        {
            this.NPMHIPAACertDataDependents = new HashSet<NPMHIPAACertDataDependent>();
        }
    
        public int NPMHIPAACertDataID { get; set; }
        public int MemberID { get; set; }
        public string MedicalPlanName { get; set; }
        public System.DateTime OriginalEnrollmentDate { get; set; }
        public Nullable<System.DateTime> LastDayOfCoverage { get; set; }
        public string CoverageLevel { get; set; }
    
        public virtual NPM NPM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NPMHIPAACertDataDependent> NPMHIPAACertDataDependents { get; set; }
    }
}
