//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBDependentPlan
    {
        public int QBDependentPlanID { get; set; }
        public int QBDependentID { get; set; }
        public string InsuranceType { get; set; }
        public Nullable<System.DateTime> FDOC { get; set; }
        public Nullable<System.DateTime> LDOC { get; set; }
        public string PlanName { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CarrierPlanIdentification { get; set; }
        public string BundleName { get; set; }
        public int ClientPlanQBID { get; set; }
    
        public virtual ClientPlanQB ClientPlanQB { get; set; }
        public virtual QBDependent QBDependent { get; set; }
    }
}
