//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBPlanCarrierSubcode
    {
        public int QBPlanCarrierSubcodeID { get; set; }
        public int QBPlanID { get; set; }
        public int ClientPlanQBID { get; set; }
        public int MemberID { get; set; }
        public string CarrierSubcodeType { get; set; }
        public string DataValue { get; set; }
        public string CarrierSubcode { get; set; }
    
        public virtual ClientPlanQB ClientPlanQB { get; set; }
        public virtual QBPlan QBPlan { get; set; }
    }
}
