//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBPlan
    {
        public int QBPlanID { get; set; }
        public int MemberID { get; set; }
        public string InsuranceType { get; set; }
        public Nullable<System.DateTime> FDOC { get; set; }
        public Nullable<System.DateTime> LDOC { get; set; }
        public Nullable<int> MonthsOfCOBRA { get; set; }
        public Nullable<int> DaysToElect { get; set; }
        public Nullable<int> InitialPaymentGracePeriod { get; set; }
        public Nullable<int> SubsequentPaymentGracePeriod { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<System.DateTime> ElectionPostMarkDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public string PlanName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CarrierPlanIdentification { get; set; }
        public string CoverageLevel { get; set; }
        public string BundleName { get; set; }
        public Nullable<bool> IsElected { get; set; }
        public int ClientPlanQBID { get; set; }
        public Nullable<decimal> NumberOfUnits { get; set; }
    }
}
