//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBStateInsert
    {
        public int QBStateInsertID { get; set; }
        public int MemberID { get; set; }
        public string InsertName { get; set; }
        public string InsertDescription { get; set; }
    }
}
