//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPM
    {
        public int MemberID { get; set; }
        public int ClientDivisionID { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> EnteredDateTime { get; set; }
        public string EnteredByUser { get; set; }
        public int ClientID { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string IndividualID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string TobaccoUse { get; set; }
        public string EmployeeType { get; set; }
        public string PayrollType { get; set; }
        public Nullable<int> YearsOfService { get; set; }
        public string PremiumCouponType { get; set; }
        public Nullable<int> CurrentlyHasCOBRARights { get; set; }
        public Nullable<int> WillHaveCOBRARightsOnTermination { get; set; }
        public string BillingStartDate { get; set; }
        public string BillingEndDate { get; set; }
        public string BillingFrequency { get; set; }
        public string BillingType { get; set; }
        public Nullable<int> IsSPMLegacy { get; set; }
        public Nullable<int> Migrated { get; set; }
        public string HIPAAEnrollmentDate { get; set; }
        public Nullable<int> GracePeriodNumberOfDays { get; set; }
        public string MethodEntered { get; set; }
        public string PaidThroughDate { get; set; }
        public string BenefitGroup { get; set; }
        public string AccountStructure { get; set; }
        public string ClientCustomData { get; set; }
        public Nullable<int> AllowSSO { get; set; }
        public string SSOIdentifier { get; set; }
        public string LastModifiedDate { get; set; }
        public string PlanCategory { get; set; }
        public string InitialGracePeriodDate { get; set; }
        public Nullable<int> InitialGracePeriodDays { get; set; }
        public string SPMInitialGracePeriodOptionType { get; set; }
        public string SSN { get; set; }
    }
}
