//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPMACH
    {
        public int SPMACHID { get; set; }
        public int MemberID { get; set; }
        public string ACHStatus { get; set; }
        public Nullable<bool> IsACHDateSelection { get; set; }
        public Nullable<System.DateTime> NextPaymentDate { get; set; }
    
        public virtual SPM SPM { get; set; }
    }
}
