//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPMOpenEnrollment
    {
        public int MemberID { get; set; }
        public string MemberEntityType { get; set; }
        public int EnrollmentPeriodID { get; set; }
        public string PlanType { get; set; }
        public string PlanName { get; set; }
        public int IsSelected { get; set; }
        public string SelectedCoverageLevel { get; set; }
        public string SelectedDependents { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public string BillingFrequency { get; set; }
        public string PlanYearName { get; set; }
        public System.DateTime PlanYearStartDate { get; set; }
        public System.DateTime PlanYearEndDate { get; set; }
        public System.DateTime EnrollmentStartDate { get; set; }
        public System.DateTime EnrollmentEndDate { get; set; }
        public string NotificationPreference { get; set; }
        public Nullable<System.DateTime> NotificationQueueDay { get; set; }
        public Nullable<System.DateTime> FirstEnrollmentReminder { get; set; }
        public Nullable<System.DateTime> SecondEnrollmentReminder { get; set; }
        public Nullable<System.DateTime> ThirdEnrollmentReminder { get; set; }
        public string MemberStatus { get; set; }
        public string EnrollmentPeriodMigrationType { get; set; }
    }
}
