//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPMPayment
    {
        public int SPMPaymentID { get; set; }
        public int MemberID { get; set; }
        public Nullable<System.DateTime> EnteredDateTime { get; set; }
        public System.DateTime PostmarkDate { get; set; }
        public System.DateTime DepositDate { get; set; }
        public decimal PaymentAmount { get; set; }
        public string PaymentMethod { get; set; }
        public string CheckNumber { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.Guid> EnteredUser { get; set; }
        public bool IsVoid { get; set; }
        public Nullable<System.DateTime> VoidDate { get; set; }
        public string VoidReason { get; set; }
        public Nullable<System.Guid> VoidUser { get; set; }
        public Nullable<decimal> AllocatedAmount { get; set; }
        public string PlanName { get; set; }
        public Nullable<decimal> EmployeeSubsidy { get; set; }
        public Nullable<decimal> AEISubsidy { get; set; }
        public Nullable<decimal> AdminFee { get; set; }
        public Nullable<decimal> PremiumAmount { get; set; }
        public Nullable<System.DateTime> PremiumDueDate { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<decimal> ConvenienceFee { get; set; }
        public Nullable<decimal> PartnerConvenienceFee { get; set; }
        public Nullable<decimal> TotalConvenienceFee { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
        public virtual AdminUser AdminUser1 { get; set; }
        public virtual SPM SPM { get; set; }
    }
}
