//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPMPlan
    {
        public int SPMPlanID { get; set; }
        public int MemberID { get; set; }
        public int ClientPlanSPMID { get; set; }
        public Nullable<System.DateTime> FirstDayOfCoverage { get; set; }
        public Nullable<System.DateTime> LastDayOfCoverage { get; set; }
        public Nullable<int> GracePeriodNumberOfDays { get; set; }
        public string PlanName { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int CarrierID { get; set; }
        public string CoverageLevel { get; set; }
        public string BundleName { get; set; }
        public Nullable<decimal> BookableAdminFeeFlatAmount { get; set; }
        public Nullable<decimal> BookableAdminFeePercentAmount { get; set; }
        public Nullable<decimal> RemittableAdminFeeFlatAmount { get; set; }
        public Nullable<decimal> RemittableAdminFeePercentAmount { get; set; }
        public Nullable<decimal> NumberOfUnits { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<System.DateTime> RatePeriodEffectiveDate { get; set; }
        public Nullable<System.DateTime> RatePeriodEnddate { get; set; }
    
        public virtual Carrier Carrier { get; set; }
        public virtual ClientPlanSPM ClientPlanSPM { get; set; }
    }
}
