//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPMSubsidySchedule
    {
        public int SPMSubsidyScheduleID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Type { get; set; }
        public string AmountType { get; set; }
        public decimal Amount { get; set; }
        public string InsuranceType { get; set; }
        public int MemberID { get; set; }
    
        public virtual SPM SPM { get; set; }
    }
}
