//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessing.DataModels.CobraPoint
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPMScheduledPayment
    {
        public int SPMSchedulePaymentID { get; set; }
        public int MemberID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> DaysAfterDueDateToRecordPayment { get; set; }
        public string ScheduledPaymentType { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual SPM SPM { get; set; }
    }
}
